Repository LM-channel-team-project/team23, pull requests merged in 2021-06, with the labels that each got.

#100 bug 수정
  server/routes/User.ts
Labels: bug

#108 로그아웃 기능 개선
  client/src/Components/Common/Header.tsx
  client/src/Components/Common/LoginAndSignupModal.tsx
  client/src/Components/Common/ProfileModal.tsx
  client/src/api/auth.ts
  client/src/hoc/auth.tsx
  server/models/User.interface.ts
  server/models/User.ts
  server/routes/User.ts
Labels: enhancement

#110 fix: 마이페이지 정보창 기능 개선
  client/src/Components/Mypage/ProfilePage.tsx
  client/src/Components/Mypage/TagInput.tsx
Labels: enhancement

#111 프로젝트 작성 완료 시 서버에 저장 기능 추가
  client/src/Components/BuildProject/ProjectDuration.tsx
  client/src/Pages/BuildProject/BuildProject.tsx
  server/routes/Project.ts
  uploads/projects/1622636864583_1.jpg
  uploads/projects/descriptions/1622635669160_desc.txt
  uploads/projects/descriptions/1622636864799_desc.txt
Labels: feature

#116 Project Summary 추가
  client/src/Pages/BuildProject/BuildProject.tsx
  client/yarn.lock
  server/models/Project.ts
  uploads/projects/descriptions/1622806388726_desc.txt
Labels: enhancement

#120 feat: Project Page 구현
  client/src/Components/Common/OptionData.ts
  client/src/Components/Mypage/InfoBox.tsx
  client/src/Components/Project/ProjectBox.tsx
  client/src/Components/Project/ProjectHeader.tsx
  client/src/Components/Project/ProjectRecommendBox.tsx
  client/src/Components/Project/ProjectSearchOption.tsx
  client/src/Pages/BuildProject/BuildProject.tsx
  client/src/Pages/Home/Home.tsx
  client/src/Pages/Project/Project.tsx
  server/routes/Project.ts
  uploads/projects/descriptions/1623034263405_desc.txt
  uploads/projects/descriptions/1623035168367_desc.txt
  uploads/projects/descriptions/1623035411537_desc.txt
  uploads/projects/descriptions/1623035468530_desc.txt
  uploads/projects/descriptions/1623035596759_desc.txt
Labels: feature

#119 메인 페이지 유저,프로젝트 불러오기
  .gitignore
  client/src/Components/Project/ProjectBox.tsx
  client/src/Pages/Home/Home.tsx
  server/models/Project.interface.ts
  server/models/User.interface.ts
  server/routes/Project.ts
  server/routes/User.ts
  uploads/projects/descriptions/1623070147192_desc.txt
  uploads/projects/descriptions/1623152408053_desc.txt
  yarn.lock
Labels: feature

#127 유저 & 프로젝트 좋아요 기능 추가
  client/src/Components/Common/LikeButton.tsx
  client/src/Components/People/PeopleListItem.tsx
  client/src/Components/Project/ProjectBox.tsx
  client/src/Components/Project/ProjectBoxList.tsx
  client/src/Pages/Home/Home.tsx
  client/src/Pages/People/PeoplePresenter.tsx
  server/models/Like.interface.ts
  server/models/Like.ts
  server/routes/Like.ts
Labels: feature

#128 feat: 프로젝트 디테일 페이지 구현
  client/src/Components/People/PeopleListItem.tsx
  client/src/Components/Project/ProjectDetail/Info.tsx
  client/src/Components/Project/ProjectDetail/Management.tsx
  client/src/Components/Project/ProjectDetail/ProjectDetailHeader.tsx
  client/src/Components/Project/ProjectDetail/RightMenu.tsx
  client/src/Components/Project/ProjectDetail/Status.tsx
  client/src/Pages/Project/ProjectDetail/ProjectDetail.tsx
  client/src/Pages/UpdateProject/UpdateProject.tsx
  client/src/Pages/UpdateProject/index.tsx
  client/src/Routers.tsx
  server/routes/ManageProject.ts
  server/routes/Project.ts
Labels: feature

#129 people 디테일 페이지 구현
  client/package.json
  client/src/App.tsx
  client/src/Components/Common/Header.tsx
  client/src/Components/Common/SimpleModal.tsx
  client/src/Components/Common/transformValue.ts
  client/src/Components/People/PeopleDetail/ChattingModalContents.tsx
  client/src/Components/People/PeopleDetail/ImgContainer.tsx
  client/src/Components/People/PeopleDetail/ProjectInvitedContents.tsx
  client/src/Components/People/PeopleDetail/ProjectTab.tsx
  client/src/Components/People/PeopleDetail/UserInfoBox.tsx
  client/src/Components/People/PeopleDetail/UserInfoTop.tsx
  client/src/Components/People/PeopleListItem.tsx
  client/src/Components/People/Recommend/PeopleRecommendTable.tsx
  client/src/Components/People/Recommend/PeopleRecommendUser.tsx
  client/src/Components/Project/ProjectBox.tsx
  client/src/Pages/BuildProject/BuildProject.tsx
  client/src/Pages/People/PeopleDetail/PeopleDetailPresenter.tsx
  client/src/Pages/People/PeoplePresenter.tsx
  client/src/api/users.ts
  client/src/modules/auth.ts
  client/src/modules/index.ts
  client/src/modules/userInfo.ts
  package-lock.json
  package.json
  server/models/User.interface.ts
  server/models/User.ts
  server/models/UserRole.ts
  server/routes/User.ts
Labels: bug, enhancement

#134 프로젝트 상세 페이지 기능 구현
  client/src/Components/Project/ProjectDetail/Comment.tsx
  client/src/Components/Project/ProjectDetail/Info.tsx
  client/src/Components/Project/ProjectDetail/Management.tsx
  client/src/Components/Project/ProjectDetail/Question.tsx
  client/src/Components/Project/ProjectDetail/Status.tsx
  client/src/Components/Project/ProjectDetail/UserInfo.tsx
  client/src/Pages/Project/ProjectDetail/ProjectDetail.tsx
  server/models/Comment.ts
  server/models/Commet.interface.ts
  server/models/UserRole.interface.ts
  server/models/UserRole.ts
  server/routes/Comment.ts
  server/routes/ManageProject.ts
  server/routes/Project.ts
Labels: feature

#133 좋아요 관련 기능 개선 및 추가
  client/package.json
  client/src/App.tsx
  client/src/Components/Common/LikeButton.tsx
  client/src/Components/Common/LoginAndSignupModal.tsx
  client/src/Components/Common/ProfileModal.tsx
  client/src/Components/Mypage/ImgInfo.tsx
  client/src/Components/Mypage/InfoBox.tsx
  client/src/Components/People/PeopleList.tsx
  client/src/Components/People/PeopleListItem.tsx
  client/src/Components/People/Recommend/PeopleRecommendTable.tsx
  client/src/Components/Project/ProjectBox.tsx
  client/src/Components/Project/ProjectDetail/RightMenu.tsx
  client/src/Pages/Home/Home.tsx
  client/src/Pages/Mypage/Mypage.tsx
  client/src/Pages/People/PeopleDetail/PeopleDetailPresenter.tsx
  client/src/Pages/People/PeoplePresenter.tsx
  client/src/Pages/Project/Project.tsx
  client/src/Pages/Project/ProjectDetail/ProjectDetail.tsx
  client/src/api/home.ts
  client/src/api/like.ts
  client/src/api/types/index.ts
  client/src/modules/home.ts
  client/src/modules/index.ts
  client/src/modules/like.ts
  client/yarn.lock
  package.json
  server/models/Like.ts
  server/routes/Like.ts
  server/routes/ManageProject.ts
  yarn.lock
Labels: enhancement, feature
