Repository LM-channel-team-project/team23, pull requests merged in 2021-05, with the labels that each got.

#51 Signup Validation
  client/src/Components/Common/Header.tsx
  client/src/Components/Common/LoginAndSignupModal.tsx
  client/src/Components/Common/ProfileModal.tsx
  client/src/Components/Project/ProjectDetail/Comment.tsx
  client/src/Components/Project/ProjectDetail/Info.tsx
  client/src/Components/Project/ProjectDetail/ProjectDetailHeader.tsx
  client/src/Components/Project/ProjectDetail/ProjectTab.tsx
  client/src/Components/Project/ProjectDetail/Question.tsx
  client/src/Components/Project/ProjectDetail/Reference.tsx
  client/src/Components/Project/ProjectDetail/RightMenu.tsx
  client/src/Components/Project/ProjectDetail/Status.tsx
  client/src/Pages/Login/Login.tsx
  client/src/Pages/Login/index.tsx
  client/src/Pages/Project/ProjectDetail/ProjectDetail.tsx
  client/src/Pages/Project/ProjectDetail/index.tsx
  client/src/Pages/Signup/SignupModal.tsx
  client/src/Routers.tsx
  client/src/img/check_icon.svg
  client/yarn.lock
Labels: enhancement

#57 로그인 후 헤더 프로필 클릭시 모달 생성 처리
  client/src/Components/Common/Header.tsx
  client/src/Components/Common/LoginAndSignupModal.tsx
  client/src/Components/Common/ProfileModal.tsx
Labels: feature

#58 프로젝트 생성 페이지 옵션 추가
  client/src/Components/Project/ProjectSearchOption.tsx
  client/src/Pages/BuildProject/BuildProject.tsx
  package.json
  yarn.lock
Labels: enhancement, feature

#68 feat: Add Project Management Tab
  client/package.json
  client/src/Components/Project/ProjectDetail/Management.tsx
  client/src/Components/Project/ProjectDetail/ProjectTab.tsx
  client/src/Components/Project/ProjectDetail/UserInfo.tsx
  client/src/Pages/Project/ProjectDetail/ProjectDetail.tsx
  client/src/Routers.tsx
Labels: feature

#66 마이페이지 관심 분야 Text Input 추가
  client/src/Components/Mypage/ProfilePage.tsx
Labels: enhancement

#67 Button, Select, Input 컴포넌트화 한 것 각 페이지에 적용
  client/src/Components/Common/Button.tsx
  client/src/Components/Common/Header.tsx
  client/src/Components/Common/LoginAndSignupModal.tsx
  client/src/Components/Common/OptionData.ts
  client/src/Components/Common/SelectBox.tsx
  client/src/Components/People/PeopleSearchOption.tsx
  client/src/Components/Project/ProjectDetail/ProjectTab.tsx
  client/src/Components/Project/ProjectDetail/RightMenu.tsx
  client/src/Components/Project/ProjectDetail/Status.tsx
  client/src/Components/Project/ProjectSearchOption.tsx
  client/src/Pages/BuildProject/BuildProject.tsx
Labels: enhancement, feature

#69 myprofile : 이미지 업로드, 이미지 미리보기, 서버에 저장
  client/package.json
  client/src/Components/Mypage/ImgInfo.tsx
  package-lock.json
  server/app.ts
Labels: enhancement

#72 ProjectBox 클릭 시 해당 ProjectDetail 페이지로 이동
  client/src/Components/Mypage/InfoBox.tsx
  client/src/Components/Project/ProjectBox.tsx
  client/src/Pages/Home/Home.tsx
  client/src/Pages/Project/Project.tsx
Labels: feature

#75 feat: Add Link at PeopleListItem
  client/src/Components/People/PeopleList.tsx
  client/src/Components/People/PeopleListItem.tsx
  client/src/Components/People/Recommend/PeopleRecommendTable.tsx
  client/src/Components/People/Recommend/PeopleRecommendUser.tsx
  client/src/Components/People/userDB.tsx
  client/src/Pages/Home/Home.tsx
  client/src/Pages/People/PeopleComponents.tsx
Labels: feature

#79 프로젝트 작성 페이지 체크 박스 기능 추가
  client/src/Components/Common/Checkbox.tsx
  client/src/Components/Project/ProjectSearchOption.tsx
  client/src/Pages/BuildProject/BuildProject.tsx
  client/yarn.lock
Labels: enhancement

#81 프로젝트 작성 페이지 프로젝트 샘플 이미지 클릭시 썸네일 추가
  client/src/Components/BuildProject/sampleImages.ts
  client/src/Pages/BuildProject/BuildProject.tsx
Labels: feature

#87 /my 접속 시 발생 경고 해결
  client/src/Components/Mypage/ProfilePage.tsx
  client/yarn.lock
  server/app.ts
  server/db.ts
  server/routes/Project.ts
  yarn.lock
Labels: bug

#91 프로젝트 작성 페이지 Input 추가,삭제 기능 추가
  client/src/Components/BuildProject/RecruitSelect.tsx
  client/src/Components/BuildProject/ReferenceInput.tsx
  client/src/Components/Common/Header.tsx
  client/src/Pages/BuildProject/BuildProject.tsx
  uploads/users/1621609073815_1621189440827_cute.jpg
Labels: feature

#92 feat: Add TagInput
  client/src/Components/Common/InputBox.tsx
  client/src/Components/Mypage/ProfilePage.tsx
  client/src/Components/Mypage/TagInput.tsx
  client/src/setupProxy.ts
  uploads/users/1622197662619_spong.jpg
Labels: feature

#95 Fix: 마이 페이지 포트폴리오 Input 추가, 삭제 수정
  client/src/Components/Mypage/PortfolioInput.tsx
  client/src/Components/Mypage/ProfilePage.tsx
Labels: bug, enhancement

#93 프로젝트 설명 텍스트 에디터 추가
  client/package.json
  client/src/Components/BuildProject/DescriptionInput.tsx
  client/src/Pages/BuildProject/BuildProject.tsx
  client/yarn.lock
Labels: enhancement

#96 프로젝트 작성 페이지 이미지 업로드 기능 추가
  client/src/Components/BuildProject/ImgUploadBtn.tsx
  client/src/Pages/BuildProject/BuildProject.tsx
  uploads/projects/1622455857948_1.jpg
  uploads/users/1622211644702_1.jpg
Labels: feature
