Repository LM-channel-team-project/team23, pull requests merged in 2021-04, with the labels that each got.

#2 CRA & ESLint & Prettier Settings
  .eslintrc
  .gitignore
  .prettierrc
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
  yarn.lock
Labels: feature

#5 폴더(파일) 구조, Router, GlobalStyles 셋팅
  package.json
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/Components/Common/GlobalStyles.tsx
  src/Components/Common/Header.tsx
  src/Pages/Home/Home.tsx
  src/Pages/Home/index.tsx
  src/Pages/Login/Login.tsx
  src/Pages/Login/index.tsx
  src/Pages/People/People.tsx
  src/Pages/People/index.tsx
  src/Pages/Project/Project.tsx
  src/Pages/Project/index.tsx
  src/Routers.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/reportWebVitals.ts
  src/setupTests.ts
  yarn.lock
Labels: feature

#14 Issue/#13 전반적인 CSS 수정
  client/public/index.html
  client/src/App.tsx
  client/src/Components/Common/Footer.tsx
  client/src/Components/Common/Header.tsx
  client/src/Components/Common/Title.tsx
  client/src/Components/Home/Info.tsx
  client/src/Components/Project/ProjectBox.tsx
  client/src/Components/Project/ProjectHeader.tsx
  client/src/Components/Project/ProjectSearchOption.tsx
  client/src/Pages/Home/Home.tsx
  client/src/Pages/Login/Login.tsx
  client/src/Pages/People/PeoplePresenter.tsx
  client/src/Pages/Project/Project.tsx
  client/src/Pages/Signup/Signup.tsx
  client/src/Pages/Signup/SignupModal.tsx
  client/src/styeld.d.ts
  client/src/theme.ts
Labels: enhancement

#16 Issue/#15 ProjectBox, ProjectBoxList 컴포넌트 분리
  client/src/Components/Project/ProjectBox.tsx
  client/src/Components/Project/ProjectBoxList.tsx
  client/src/Pages/Home/Home.tsx
  client/src/Pages/Project/Project.tsx
Labels: enhancement

#24 헤더 프로필 모달 추가
  client/src/Components/Common/Header.tsx
  client/src/Components/Common/ProfileModal.tsx
Labels: feature

#27 프로젝트 생성 페이지 추가
  client/src/Pages/BuildProject/BuildProject.tsx
  client/src/Pages/BuildProject/index.tsx
  client/src/Routers.tsx
Labels: feature

#30 Project 메인 페이지 검색 옵션 수정, 추천 프로젝트 추가
  client/src/Components/Project/Checkbox.tsx
  client/src/Components/Project/ProjectHeader.tsx
  client/src/Components/Project/ProjectRecommend.tsx
  client/src/Components/Project/ProjectRecommendBox.tsx
  client/src/Components/Project/ProjectSearchOption.tsx
  client/src/Pages/Project/Project.tsx
  client/src/styeld.d.ts
  client/src/theme.ts
Labels: enhancement

#29 마이페이지 마크업
  client/package.json
  client/src/Components/Common/ProfileModal.tsx
  client/src/Components/Mypage/InfoBox.tsx
  client/src/Components/Mypage/ProfilePage.tsx
  client/src/Components/Mypage/Tab.tsx
  client/src/Components/Mypage/alarmBox.tsx
  client/src/Components/Mypage/alarmBoxList.tsx
  client/src/Components/People/ImgInfo.tsx
  client/src/Pages/Mypage/Mypage.tsx
  client/src/Pages/Mypage/index.tsx
  client/src/Routers.tsx
  client/src/index.tsx
  client/src/styeld.d.ts
  client/src/theme.ts
Labels: feature

#32 People 컴포넌트 분리, People detail 페이지 추가
  client/package.json
  client/src/Components/Common/ProfileModal.tsx
  client/src/Components/Mypage/InfoBox.tsx
  client/src/Components/Mypage/ProfilePage.tsx
  client/src/Components/Mypage/Tab.tsx
  client/src/Components/Mypage/alarmBox.tsx
  client/src/Components/Mypage/alarmBoxList.tsx
  client/src/Components/People/ImgInfo.tsx
  client/src/Components/People/PeopleHeader.tsx
  client/src/Components/People/PeopleList.tsx
  client/src/Components/People/PeopleListItem.tsx
  client/src/Components/People/PeopleSearchOption.tsx
  client/src/Components/People/Recommend/PeopleRecommendTable.tsx
  client/src/Components/People/Recommend/PeopleRecommendUser.tsx
  client/src/Components/People/userDB.tsx
  client/src/Components/Project/Checkbox.tsx
  client/src/Components/Project/ProjectHeader.tsx
  client/src/Components/Project/ProjectRecommend.tsx
  client/src/Components/Project/ProjectRecommendBox.tsx
  client/src/Components/Project/ProjectSearchOption.tsx
  client/src/Pages/BuildProject/BuildProject.tsx
  client/src/Pages/BuildProject/index.tsx
  client/src/Pages/Mypage/Mypage.tsx
  client/src/Pages/Mypage/index.tsx
  client/src/Pages/People/PeopleDetail/PeopleDetailComponents.tsx
  client/src/Pages/People/PeopleDetail/PeopleDetailPresenter.tsx
  client/src/Pages/People/PeopleDetail/index.tsx
  client/src/Pages/People/PeoplePresenter.tsx
  client/src/Pages/Project/Project.tsx
  client/src/Routers.tsx
  client/src/index.tsx
  client/src/styeld.d.ts
  client/src/theme.ts
Labels: enhancement, feature

#41 Revert issue/#31
  client/package.json
  client/src/Components/Common/ProfileModal.tsx
  client/src/Components/Mypage/InfoBox.tsx
  client/src/Components/Mypage/ProfilePage.tsx
  client/src/Components/Mypage/Tab.tsx
  client/src/Components/Mypage/alarmBox.tsx
  client/src/Components/Mypage/alarmBoxList.tsx
  client/src/Components/People/ImgInfo.tsx
  client/src/Components/People/PeopleHeader.tsx
  client/src/Components/People/PeopleList.tsx
  client/src/Components/People/PeopleListItem.tsx
  client/src/Components/People/PeopleSearchOption.tsx
  client/src/Components/People/Recommend/PeopleRecommendTable.tsx
  client/src/Components/People/Recommend/PeopleRecommendUser.tsx
  client/src/Components/People/userDB.tsx
  client/src/Components/Project/Checkbox.tsx
  client/src/Components/Project/ProjectHeader.tsx
  client/src/Components/Project/ProjectRecommend.tsx
  client/src/Components/Project/ProjectRecommendBox.tsx
  client/src/Components/Project/ProjectSearchOption.tsx
  client/src/Pages/BuildProject/BuildProject.tsx
  client/src/Pages/BuildProject/index.tsx
  client/src/Pages/Mypage/Mypage.tsx
  client/src/Pages/Mypage/index.tsx
  client/src/Pages/People/PeopleDetail/PeopleDetailComponents.tsx
  client/src/Pages/People/PeopleDetail/PeopleDetailPresenter.tsx
  client/src/Pages/People/PeopleDetail/index.tsx
  client/src/Pages/People/PeoplePresenter.tsx
  client/src/Pages/Project/Project.tsx
  client/src/Routers.tsx
  client/src/index.tsx
  client/src/styeld.d.ts
  client/src/theme.ts
Labels: bug

#42 issue/#31 re merge
  client/src/Routers.tsx
  client/src/styeld.d.ts
  client/src/theme.ts
Labels: bug

#46 프로젝트 상세 페이지 추가
  client/src/Components/Common/Header.tsx
  client/src/Components/Common/ProfileModal.tsx
  client/src/Components/Project/ProjectDetail/Comment.tsx
  client/src/Components/Project/ProjectDetail/Info.tsx
  client/src/Components/Project/ProjectDetail/ProjectDetailHeader.tsx
  client/src/Components/Project/ProjectDetail/ProjectTab.tsx
  client/src/Components/Project/ProjectDetail/Question.tsx
  client/src/Components/Project/ProjectDetail/Reference.tsx
  client/src/Components/Project/ProjectDetail/RightMenu.tsx
  client/src/Components/Project/ProjectDetail/Status.tsx
  client/src/Pages/Project/ProjectDetail/ProjectDetail.tsx
  client/src/Pages/Project/ProjectDetail/index.tsx
  client/src/Routers.tsx
  client/src/img/check_icon.svg
  client/yarn.lock
Labels: feature
