Repository LM-channel-team-project/team23, pull requests merged in 2021-07, with the labels that each got.

#142 feat: 마이 페이지 프로젝트 탭 기능 구현
  client/src/Components/Project/ProjectDetail/Info.tsx
  client/src/Pages/Mypage/Mypage.tsx
  server/routes/ManageProject.ts
  server/routes/Project.ts
Labels: feature

#139 이미지 표시 오류 해결
  client/src/Components/Mypage/ImgInfo.tsx
  client/src/Components/Mypage/ProfilePage.tsx
  client/src/Components/People/PeopleDetail/ImgContainer.tsx
  client/src/Components/Project/ProjectDetail/ProjectDetailHeader.tsx
  client/src/Components/Project/ProjectDetail/Question.tsx
  client/src/Components/Project/ProjectDetail/RightMenu.tsx
  client/src/Pages/BuildProject/BuildProject.tsx
  client/src/Pages/UpdateProject/UpdateProject.tsx
Labels: bug, enhancement

#141 Issue/#130
  client/src/Components/BuildProject/sampleImages.ts
  client/src/Components/Common/AlarmModalContents.tsx
  client/src/Components/Common/Footer.tsx
  client/src/Components/Common/Header.tsx
  client/src/Components/Common/InvitedProject.tsx
  client/src/Components/Common/LoginAndSignupModal.tsx
  client/src/Components/Common/PersonalAlarmData.ts
  client/src/Components/Common/ProfileModal.tsx
  client/src/Components/Common/Recruit.tsx
  client/src/Components/Common/SimpleModal.tsx
  client/src/Components/Common/chatRequest.tsx
  client/src/Components/Mypage/InfoBox.tsx
  client/src/Components/Mypage/alarmBox.tsx
  client/src/Components/People/PeopleDetail/ChattingModalContents.tsx
  client/src/Components/People/PeopleDetail/ProjectInvitedContents.tsx
  client/src/Components/People/PeopleDetail/UserInfoBox.tsx
  client/src/Components/People/PeopleDetail/UserInfoTop.tsx
  client/src/Components/People/PeopleListItem.tsx
  client/src/Pages/Mypage/Mypage.tsx
  client/src/Pages/People/PeoplePresenter.tsx
  client/src/Pages/Project/ProjectDetail/ProjectDetail.tsx
  client/src/api/alarm.ts
  client/src/api/auth.ts
  client/src/api/types/alarm.ts
  client/src/hook/useCreateAlarm.ts
  client/src/modules/home.ts
  client/src/modules/userInfo.ts
  server/routes/Alarm.ts
  server/routes/Project.ts
  server/routes/User.ts
Labels: bug, enhancement

#150 README 작성
  README.md
Labels: documentation
